force-app/main/default/objects/Meta_de_Venta__c/Meta_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Meta de Venta</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Meta de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metas de Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meta_de_Venta__c/fields/Anio__c.field-meta.xml
<CustomField>
    <fullName>Anio__c</fullName>
    <label>Año</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meta_de_Venta__c/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Metas_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meta_de_Venta__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Versión</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCORD EXL-T</fullName>
            </value>
            <value>
                <fullName>CIVIC EX CVT</fullName>
            </value>
            <value>
                <fullName>CIVIC SI MT</fullName>
            </value>
            <value>
                <fullName>CIVIC TYPE R</fullName>
            </value>
            <value>
                <fullName>CR-V CITY PLUS 2WD</fullName>
            </value>
            <value>
                <fullName>CR-V EXL 1.5T 4WD</fullName>
            </value>
            <value>
                <fullName>CR-V PRESTIGE 2WD</fullName>
            </value>
            <value>
                <fullName>FIT EX CVT</fullName>
            </value>
            <value>
                <fullName>HR-V EX 2WD</fullName>
            </value>
            <value>
                <fullName>HR-V EXL PRESTIGE 2WD</fullName>
            </value>
            <value>
                <fullName>HR-V LX 2WD</fullName>
            </value>
            <value>
                <fullName>HR-V LX 2WD X-TYLE</fullName>
            </value>
            <value>
                <fullName>ODYSSEY EXLN-REST</fullName>
            </value>
            <value>
                <fullName>PILOT EXL 4WD</fullName>
            </value>
            <value>
                <fullName>PILOT EXL PRESTIGE 2WD</fullName>
            </value>
            <value>
                <fullName>WR-V LX CVT 2WD</fullName>
            </value>
            <value>
                <fullName>WR-V LX MT 2WD</fullName>
            </value>
            <value>
                <fullName>WR-V EX 2WD</fullName>
            </value>
            <value>
                <fullName>USADOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Meta_asesor__c.field-meta.xml
<CustomField>
    <fullName>Meta_asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meta asesor</label>
    <referenceTo>Meta_de_Venta__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Meta_GerenteGeneral__c.field-meta.xml
<CustomField>
    <fullName>Meta_GerenteGeneral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meta GerenteGeneral</label>
    <referenceTo>Meta_de_Venta__c</referenceTo>
    <relationshipLabel>Opportunity Product (Cuota GerenteGeneral)</relationshipLabel>
    <relationshipName>Opportunity_Product2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Meta_Manager__c.field-meta.xml
<CustomField>
    <fullName>Meta_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meta Manager</label>
    <referenceTo>Meta_de_Venta__c</referenceTo>
    <relationshipLabel>Opportunity Product (Cuota Manager)</relationshipLabel>
    <relationshipName>Opportunity_Product1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MetaVentaTriggerHandler.cls
//Made by me, August 2021
public class MetaVentaTriggerHandler extends TriggerHandler{
    //Listas de MetaVenta
    private list<Meta_de_Venta__c> newMetaVentaList;
    
    //Mapa de MetaVenta de tipo id, MetaVenta
    private Map<Id, Meta_de_Venta__c> newMetaVentaMap;
    private Map<Id, Meta_de_Venta__c> oldMetaVentaMap;

    public MetaVentaTriggerHandler() {
        //Cargamos la lista de Opportunity con lo que viene en el contexto de trigger.new
        newMetaVentaList = (list<Meta_de_Venta__c>) Trigger.New;
        
        //Cargamos el mapa de Opportunity con lo que viene en el contexto de trigger.newmap
        newMetaVentaMap = (Map<Id, Meta_de_Venta__c>) Trigger.NewMap;
        
        //Cargamos el mapa de Opportunity con lo que viene en el contexto de trigger.oldmap
        oldMetaVentaMap = (Map<Id, Meta_de_Venta__c>) Trigger.OldMap;
        
    }
    
    public override void afterInsert(){
        
        set<string> setFamilias = new set<String>();
        for (Meta_de_Venta__c mv: newMetaVentaList){
            setFamilias.add(mv.Version__c);
        }
        
        system.debug('setFamilias: ' + setFamilias);
        
        //User GGAutos
        User usuarioGGAutos = [select Id from User where userName=:Label.UserNameGGAutos];
        
        //look for olis with the families in new Meta Ventas 
        list<OpportunityLineItem> lstOlis = [select Id,Product2.Family, Opportunity.OwnerId, Opportunity.Owner.ManagerId from OpportunityLineItem where Opportunity.StageName in ('P5','PU') and Product2.Family in:setFamilias ];
        list<OpportunityLineItem> lstOlisUpdate = new list<OpportunityLineItem>();
        //look for meta de Venta for Opportunity ownerId and Owner.Manager Id
        String mesActual = monthNames.get(system.today().month());
        String anioActual = String.valueof(system.today().year());
        list<Meta_de_Venta__c> listaMetaVentas = [select Id,Version__c,Asesor__c from Meta_de_Venta__c where Version__c in:setFamilias and Mes__c=:mesActual and Anio__c=:anioActual];
        map<String, map<Id,Meta_de_Venta__c>> mapMetasxVersionxUsuario = new map<String, map<Id,Meta_de_Venta__c>>(); //meta de ventas por usuario agrupados por versión
        for (Meta_de_Venta__c mv: listaMetaVentas){
            if (!mapMetasxVersionxUsuario.containsKey(mv.Version__c)) mapMetasxVersionxUsuario.put(mv.Version__c, new map<Id,Meta_de_Venta__c>());
            mapMetasxVersionxUsuario.get(mv.Version__c).put(mv.Asesor__c, mv);
        }
        
        for (OpportunityLineItem oli: lstOlis){
            map<Id,Meta_de_Venta__c> mapVentasxUsuario = mapMetasxVersionxUsuario.get(oli.Product2.Family);
            if (mapVentasxUsuario!=null){
            	oli.Meta_asesor__c = mapVentasxUsuario.get(oli.Opportunity.OwnerId)?.Id; 
                oli.Meta_Manager__c = mapVentasxUsuario.get(oli.Opportunity.Owner.ManagerId)?.Id;
                oli.Meta_GerenteGeneral__c = mapVentasxUsuario.get(usuarioGGAutos.Id)?.Id;
                lstOlisUpdate.add(oli);
            }
        }
        
        batchMetaVentaUpdatingOlis shn = new batchMetaVentaUpdatingOlis(lstOlisUpdate); 
        database.executeBatch(shn, 1);
        
    }
    
    Map<Integer,String> monthNames = new Map<Integer,String>{
        1 => 'Enero',
        2 => 'Febrero',
        3 => 'Marzo',
        4 => 'Abril',
        5 => 'Mayo',
        6 => 'Junio',
        7 => 'Julio',
        8 => 'Agosto',
        9 => 'Septiembre',
        10 => 'Octubre',
        11 => 'Noviembre',
        12 => 'Diciembre'
    };
}