force-app/main/default/objects/Account/fields/Actividad_economica__c.field-meta.xml
<CustomField>
    <fullName>Actividad_economica__c</fullName>
    <label>Actividad económica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrativa</fullName>
            </value>
            <value>
                <fullName>Agricultura/Ganaderia</fullName>
            </value>
            <value>
                <fullName>Alimentos y bebidas</fullName>
            </value>
            <value>
                <fullName>Comercializadora</fullName>
            </value>
            <value>
                <fullName>Construccion</fullName>
            </value>
            <value>
                <fullName>Consultoria y Asesoria Empresarial</fullName>
            </value>
            <value>
                <fullName>Deportista</fullName>
            </value>
            <value>
                <fullName>Educacion</fullName>
            </value>
            <value>
                <fullName>Entretenimiento</fullName>
            </value>
            <value>
                <fullName>Financiera</fullName>
            </value>
            <value>
                <fullName>Hotelería y Turísmo</fullName>
            </value>
            <value>
                <fullName>Ingenieria</fullName>
            </value>
            <value>
                <fullName>Jubilado/Pensionado</fullName>
            </value>
            <value>
                <fullName>Juridica</fullName>
            </value>
            <value>
                <fullName>Mantenimiento/Reparacion</fullName>
            </value>
            <value>
                <fullName>Mercadeo</fullName>
            </value>
            <value>
                <fullName>Otros servicios (peluquerias lavanderia etc)</fullName>
            </value>
            <value>
                <fullName>Producción/Fabrica</fullName>
            </value>
            <value>
                <fullName>Recursos Humanos</fullName>
            </value>
            <value>
                <fullName>Salud</fullName>
            </value>
            <value>
                <fullName>Seguridad</fullName>
            </value>
            <value>
                <fullName>Servicios generales (aseo vigilancia mensajeria)</fullName>
            </value>
            <value>
                <fullName>Sistemas</fullName>
            </value>
            <value>
                <fullName>Tecnología</fullName>
            </value>
            <value>
                <fullName>Textil</fullName>
            </value>
            <value>
                <fullName>Transporte</fullName>
            </value>
            <value>
                <fullName>Ventas</fullName>
            </value>
            <value>
                <fullName>Estudiante</fullName>
            </value>
            <value>
                <fullName>Ama de Casa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Direccion__c.field-meta.xml
<CustomField>
    <fullName>AM_Direccion__c</fullName>
    <description>Req. ID AM-006. Concatenación de campos para obtener la dirección.</description>
    <formula>/*
TRIM(TEXT(AM_Via_principal__c) &amp;IF(ISNULL(AM_Numero_via_principal__c),&quot;&quot;,&quot; &quot;)&amp; TEXT(AM_Numero_via_principal__c) &amp; AM_Literal_via_principal__c &amp; IF(AM_BIS__c = true, &quot; BIS&quot;, &quot;&quot;) &amp; IF(ISNULL(TEXT(AM_Orientacion_via_principal__c)),&quot;&quot;,&quot; &quot;) &amp; TEXT(AM_Orientacion_via_principal__c) &amp; IF(ISNULL(AM_Numero_via_secundaria__c),&quot;&quot;,&quot; &quot;) &amp; TEXT(AM_Numero_via_secundaria__c) &amp; IF(ISNULL(AM_Literal_via_secundaria__c ),&quot;&quot;,&quot; &quot;) &amp; AM_Literal_via_secundaria__c &amp; IF(AM_BIS2__c = true, &quot; BIS&quot;, &quot;&quot;) &amp; IF(ISNULL(TEXT(AM_Orientacion_via_secundaria__c)),&quot;&quot;,&quot; &quot;) &amp; TEXT(AM_Orientacion_via_secundaria__c) &amp;IF(ISNULL(AM_ID_cuadra__c ),&quot;&quot;,&quot; &quot;)&amp; AM_ID_cuadra__c &amp; IF(ISNULL(TEXT(Prefijo_Complemento__c )),&quot;&quot;,&quot; &quot;)&amp;TEXT(Prefijo_Complemento__c)&amp;IF(ISNULL(AM_Complemento__c),&quot;&quot;,&quot; &quot;) &amp; AM_Complemento__c&amp;IF(ISNULL( AM_Barrio__c ),&quot;&quot;,&quot; &quot;) &amp;AM_Barrio__c)
*/
substitute( SUBSTITUTE( 
TRIM(TEXT(AM_Via_principal__c) &amp; &quot; &quot; &amp; TEXT(AM_Numero_via_principal__c) &amp; AM_Literal_via_principal__c &amp; &quot; &quot; &amp; IF(AM_BIS__c = true, &quot;BIS&quot;, &quot;&quot;) &amp; &quot; &quot; &amp; TEXT(AM_Orientacion_via_principal__c) &amp; &quot; &quot; &amp; TEXT(AM_Numero_via_secundaria__c) &amp; &quot; &quot; &amp; AM_Literal_via_secundaria__c &amp; &quot; &quot; &amp; IF(AM_BIS2__c = true, &quot;BIS&quot;, &quot;&quot;) &amp; &quot; &quot; &amp; TEXT(AM_Orientacion_via_secundaria__c) &amp;&quot; &quot;&amp; AM_ID_cuadra__c &amp; &quot; &quot; &amp; AM_Complemento__c)
,&apos;  &apos;,&apos; &apos;)
,&apos;  &apos;,&apos; &apos;)</formula>
    <label>Dirección</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Literal_via_principal__c.field-meta.xml
<CustomField>
    <fullName>AM_Literal_via_principal__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección. Recibe una o dos letras que identifican la ubicación de la vía principal. Va desde la A hasta la ZZ.</description>
    <label>Literal vía principal</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Numero_via_principal__c.field-meta.xml
<CustomField>
    <fullName>AM_Numero_via_principal__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección. Recibe un número que identifica la ubicación de la vía principal</description>
    <label>Número via principal</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Numero_via_secundaria__c.field-meta.xml
<CustomField>
    <fullName>AM_Numero_via_secundaria__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección. Recibe un número que identifica la ubicación de la vía secundaria.</description>
    <label>Número via secundaria</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Ocupacion_pc__c.field-meta.xml
<CustomField>
    <fullName>AM_Ocupacion_pc__c</fullName>
    <label>Ocupacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Miembro de fuerzas armadas</fullName>
            </value>
            <value>
                <fullName>Independiente</fullName>
            </value>
            <value>
                <fullName>Jubilado/Pensionado</fullName>
            </value>
            <value>
                <fullName>Estudiante</fullName>
            </value>
            <value>
                <fullName>Dueño de empresa</fullName>
            </value>
            <value>
                <fullName>Ama de casa</fullName>
            </value>
            <value>
                <fullName>Rentista de capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Orientacion_via_principal__c.field-meta.xml
<CustomField>
    <fullName>AM_Orientacion_via_principal__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección.</description>
    <label>Orientación via principal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Norte</fullName>
            </value>
            <value>
                <fullName>Este</fullName>
            </value>
            <value>
                <fullName>Oeste</fullName>
            </value>
            <value>
                <fullName>Sur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Via_principal__c.field-meta.xml
<CustomField>
    <fullName>AM_Via_principal__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección.</description>
    <inlineHelpText>AV    Avenida
CL    Calle
CR   Carrera
CRT Carretera
CIR  Circular
CRV Circunvalar
DG   Diagonal
MZ   Manzana
VRD Vereda
LT     Lote</inlineHelpText>
    <label>Via principal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AVIAL</fullName>
                <label>Anillo vial</label>
            </value>
            <value>
                <fullName>AV</fullName>
                <label>Avenida</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bodega</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Calle</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Carrera</label>
            </value>
            <value>
                <fullName>CRT</fullName>
                <label>Carretera</label>
            </value>
            <value>
                <fullName>CIR</fullName>
                <label>Circular</label>
            </value>
            <value>
                <fullName>CRV</fullName>
                <label>Circunvalar</label>
            </value>
            <value>
                <fullName>Corregimiento</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
                <label>Diagonal</label>
            </value>
            <value>
                <fullName>KM</fullName>
                <label>Kilometro</label>
            </value>
            <value>
                <fullName>LT</fullName>
                <label>Lote</label>
            </value>
            <value>
                <fullName>MZ</fullName>
                <label>Manzana</label>
            </value>
            <value>
                <fullName>PCN</fullName>
                <label>Parcelacion</label>
            </value>
            <value>
                <fullName>TR</fullName>
                <label>Transversal</label>
            </value>
            <value>
                <fullName>URB</fullName>
                <label>Urbanizacion</label>
            </value>
            <value>
                <fullName>VTE</fullName>
                <label>Variante</label>
            </value>
            <value>
                <fullName>VRD</fullName>
                <label>Vereda</label>
            </value>
            <value>
                <fullName>VI</fullName>
                <label>Via</label>
            </value>
            <value>
                <fullName>ZN</fullName>
                <label>Zona</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Concesionario__c.field-meta.xml
<CustomField>
    <fullName>Concesionario__c</fullName>
    <formula>TEXT(Owner.AM_Concesionario__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Concesionario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Creado_en_UNOEE__c.field-meta.xml
<CustomField>
    <fullName>Creado_en_UNOEE__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esta casilla se marca cuando se confirma que el registro existe en UNOEE.</description>
    <label>Creado en UNOEE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Concesionario__c/Concesionario__c.object-meta.xml
<CustomObject>
    <description>En este objeto se maneja la información para indicar el concesionario al cual pertenece cada usuario del sistema.</description>
    <label>Concesionario / Vitrina</label>
    <nameField>
        <label>Concesionario motos / Vitrina Autos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concesionarios / Vitrinas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Concesionario__c.field-meta.xml
<CustomField>
    <fullName>Concesionario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concesionario</label>
    <referenceTo>Concesionario__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notas_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Notas_de_despacho__c</fullName>
    <label>Notas de despacho</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vitrina_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Vitrina_de_despacho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vitrina de despacho</label>
    <referenceTo>Concesionario__c</referenceTo>
    <relationshipLabel>Oportunidades (Vitrina de despacho)</relationshipLabel>
    <relationshipName>OportunidadesAutos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Concesionario__c.field-meta.xml
<CustomField>
    <fullName>Concesionario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concesionario</label>
    <referenceTo>Concesionario__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AutosCrearPedidoEnUNOEE_V2_TEST.cls
public with sharing class AutosCrearPedidoEnUNOEE_V2_TEST {
    
    // create quote 
    // sync opportunity to generate opp line only one opp line
    //create account
    public static account createAccount(Boolean toInsert ) {
        Account objAcc = new Account();
        objAcc.Creado_en_UNOEE__c       = true;
        objAcc.Name = 'Name';
       // objAcc.IsPersonAccount          = true;
        //campo Actividad economica en la cuenta relacionada antes de crear el pedido en Salesforc
        objAcc.Actividad_economica__c   ='Administrativa';        
        // l campo Dirección en la cuenta relacionada antes de crear el pedido en Sales AM_Direccion__c (FORMULA)
        objAcc.AM_Via_principal__c ='Calle';
        objAcc.AM_Numero_via_principal__c = 23;
        objAcc.AM_Literal_via_principal__c = 'a';
        objAcc.AM_Orientacion_via_principal__c = 'Sur';
        objAcc.AM_Numero_via_secundaria__c =23;
        //be tener digilenciado el campo Ocupación en la cuenta relacionada antes de crear el pedido en Salesforce.
        objAcc.AM_Ocupacion_pc__c = 'Empleado';
        if( toInsert ){
            insert objAcc; 
        }
        return objAcc;
    }
  // https://hondaautos--test2.sandbox.lightning.force.com/lightning/r/Opportunity/0060100000B9jgPAAR/view
    public static opportunity createOpportunity(Boolean toInsert, Concesionario__c objVitrina ){
        Opportunity objOpp = new Opportunity();
        // debe tener digilenciado el campo Vitrina de despacho antes de hacer el envio a UNOEE.
        objOpp.Vitrina_de_despacho__c = objVitrina.id;
        // debe tener digilenciado el campo Notas de despacho antes de hacer el envio a UNOEE.
        objOpp.Notas_de_despacho__c = 'Test notas de despacho';
        //ou have uncommitted work pending. Please commit or rollback before calling out63
        return objOpp;
    }
}