force-app/main/default/objects/Account/fields/Actividad_economica__c.field-meta.xml
<CustomField>
    <fullName>Actividad_economica__c</fullName>
    <label>Actividad económica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrativa</fullName>
            </value>
            <value>
                <fullName>Agricultura/Ganaderia</fullName>
            </value>
            <value>
                <fullName>Alimentos y bebidas</fullName>
            </value>
            <value>
                <fullName>Comercializadora</fullName>
            </value>
            <value>
                <fullName>Construccion</fullName>
            </value>
            <value>
                <fullName>Consultoria y Asesoria Empresarial</fullName>
            </value>
            <value>
                <fullName>Deportista</fullName>
            </value>
            <value>
                <fullName>Educacion</fullName>
            </value>
            <value>
                <fullName>Entretenimiento</fullName>
            </value>
            <value>
                <fullName>Financiera</fullName>
            </value>
            <value>
                <fullName>Hotelería y Turísmo</fullName>
            </value>
            <value>
                <fullName>Ingenieria</fullName>
            </value>
            <value>
                <fullName>Jubilado/Pensionado</fullName>
            </value>
            <value>
                <fullName>Juridica</fullName>
            </value>
            <value>
                <fullName>Mantenimiento/Reparacion</fullName>
            </value>
            <value>
                <fullName>Mercadeo</fullName>
            </value>
            <value>
                <fullName>Otros servicios (peluquerias lavanderia etc)</fullName>
            </value>
            <value>
                <fullName>Producción/Fabrica</fullName>
            </value>
            <value>
                <fullName>Recursos Humanos</fullName>
            </value>
            <value>
                <fullName>Salud</fullName>
            </value>
            <value>
                <fullName>Seguridad</fullName>
            </value>
            <value>
                <fullName>Servicios generales (aseo vigilancia mensajeria)</fullName>
            </value>
            <value>
                <fullName>Sistemas</fullName>
            </value>
            <value>
                <fullName>Tecnología</fullName>
            </value>
            <value>
                <fullName>Textil</fullName>
            </value>
            <value>
                <fullName>Transporte</fullName>
            </value>
            <value>
                <fullName>Ventas</fullName>
            </value>
            <value>
                <fullName>Estudiante</fullName>
            </value>
            <value>
                <fullName>Ama de Casa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AM_BIS2__c.field-meta.xml
<CustomField>
    <fullName>AM_BIS2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado en la concatenación de la dirección. Se chequea en caso de que la dirección lleve el indicador BIS en la vía secundaria.</description>
    <label>BIS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Complemento__c.field-meta.xml
<CustomField>
    <fullName>AM_Complemento__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección. Aquí se expresan los datos que complementen la dirección exacta. EJ: URB. BOSQUES DE ALEJANDRÍA APT 308.</description>
    <label>Complemento</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_ID_cuadra__c.field-meta.xml
<CustomField>
    <fullName>AM_ID_cuadra__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección. Identifica el lugar exacto en que se encuentra una edificación, después de localizar tanto la via principal como la secundaria</description>
    <label>ID cuadra</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Literal_via_principal__c.field-meta.xml
<CustomField>
    <fullName>AM_Literal_via_principal__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección. Recibe una o dos letras que identifican la ubicación de la vía principal. Va desde la A hasta la ZZ.</description>
    <label>Literal vía principal</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Literal_via_secundaria__c.field-meta.xml
<CustomField>
    <fullName>AM_Literal_via_secundaria__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección. Recibe una o dos letras que identifican la ubicación de la vía secundaria. Va desde la A hasta la ZZ.</description>
    <label>Literal vía secundaria</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Numero_via_principal__c.field-meta.xml
<CustomField>
    <fullName>AM_Numero_via_principal__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección. Recibe un número que identifica la ubicación de la vía principal</description>
    <label>Número via principal</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Orientacion_via_principal__c.field-meta.xml
<CustomField>
    <fullName>AM_Orientacion_via_principal__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección.</description>
    <label>Orientación via principal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Norte</fullName>
            </value>
            <value>
                <fullName>Este</fullName>
            </value>
            <value>
                <fullName>Oeste</fullName>
            </value>
            <value>
                <fullName>Sur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Orientacion_via_secundaria__c.field-meta.xml
<CustomField>
    <fullName>AM_Orientacion_via_secundaria__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección.</description>
    <label>Orientación via secundaria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Norte</fullName>
            </value>
            <value>
                <fullName>Este</fullName>
            </value>
            <value>
                <fullName>Oeste</fullName>
            </value>
            <value>
                <fullName>Sur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Via_principal__c.field-meta.xml
<CustomField>
    <fullName>AM_Via_principal__c</fullName>
    <description>Req. ID AM-006. Campo utilizado en la concatenación de la dirección.</description>
    <inlineHelpText>AV    Avenida
CL    Calle
CR   Carrera
CRT Carretera
CIR  Circular
CRV Circunvalar
DG   Diagonal
MZ   Manzana
VRD Vereda
LT     Lote</inlineHelpText>
    <label>Via principal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AVIAL</fullName>
                <label>Anillo vial</label>
            </value>
            <value>
                <fullName>AV</fullName>
                <label>Avenida</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bodega</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Calle</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Carrera</label>
            </value>
            <value>
                <fullName>CRT</fullName>
                <label>Carretera</label>
            </value>
            <value>
                <fullName>CIR</fullName>
                <label>Circular</label>
            </value>
            <value>
                <fullName>CRV</fullName>
                <label>Circunvalar</label>
            </value>
            <value>
                <fullName>Corregimiento</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
                <label>Diagonal</label>
            </value>
            <value>
                <fullName>KM</fullName>
                <label>Kilometro</label>
            </value>
            <value>
                <fullName>LT</fullName>
                <label>Lote</label>
            </value>
            <value>
                <fullName>MZ</fullName>
                <label>Manzana</label>
            </value>
            <value>
                <fullName>PCN</fullName>
                <label>Parcelacion</label>
            </value>
            <value>
                <fullName>TR</fullName>
                <label>Transversal</label>
            </value>
            <value>
                <fullName>URB</fullName>
                <label>Urbanizacion</label>
            </value>
            <value>
                <fullName>VTE</fullName>
                <label>Variante</label>
            </value>
            <value>
                <fullName>VRD</fullName>
                <label>Vereda</label>
            </value>
            <value>
                <fullName>VI</fullName>
                <label>Via</label>
            </value>
            <value>
                <fullName>ZN</fullName>
                <label>Zona</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Concesionario__c.field-meta.xml
<CustomField>
    <fullName>Concesionario__c</fullName>
    <formula>TEXT(Owner.AM_Concesionario__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Concesionario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/AM_CUE_Cuenta_empresarial.recordType-meta.xml
<RecordType>
    <fullName>AM_CUE_Cuenta_empresarial</fullName>
    <active>true</active>
    <description>Cuenta para empresas u organizaciones</description>
    <label>Persona Juridica</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Concesionario__c.field-meta.xml
<CustomField>
    <fullName>Concesionario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concesionario</label>
    <referenceTo>Concesionario__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Facturar_a_nombre_de__c.field-meta.xml
<CustomField>
    <fullName>Facturar_a_nombre_de__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facturar a nombre de:</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pago__c</fullName>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_de_Oportunidad__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
            <value>
                <fullName>Credito / Leasing</fullName>
            </value>
            <value>
                <fullName>Credito/Leasing + Contado</fullName>
            </value>
            <value>
                <fullName>Contado + Retoma</fullName>
            </value>
            <value>
                <fullName>Crédito / Leasing + Retoma</fullName>
            </value>
            <value>
                <fullName>Contado + Crédito + Retoma</fullName>
            </value>
            <value>
                <fullName>101 - Contado</fullName>
            </value>
            <value>
                <fullName>102 - Crédito Progreser (FORMATO TIPO CREDITO)</fullName>
            </value>
            <value>
                <fullName>103 - Cartera Propia</fullName>
            </value>
            <value>
                <fullName>104 - Negocios Especiales</fullName>
            </value>
            <value>
                <fullName>105 - Otras Financieras (FORMATO TIPO CRÉDITO)</fullName>
            </value>
            <value>
                <fullName>107 - E-commerce&quot;</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notas_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Notas_de_despacho__c</fullName>
    <label>Notas de despacho</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Se_creo_pedido_en_UNOEE__c.field-meta.xml
<CustomField>
    <fullName>Se_creo_pedido_en_UNOEE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Se creo pedido en UNOEE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vitrina__c.field-meta.xml
<CustomField>
    <fullName>Vitrina__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vitrina</label>
    <referenceTo>Concesionario__c</referenceTo>
    <relationshipLabel>Oportunidades (Vitrina)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vitrina_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Vitrina_de_despacho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vitrina de despacho</label>
    <referenceTo>Concesionario__c</referenceTo>
    <relationshipLabel>Oportunidades (Vitrina de despacho)</relationshipLabel>
    <relationshipName>OportunidadesAutos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AFOG_AutosCrearPedidoUNOEE_tst.cls
/*************************************************************************************************************
 * @name            createDataDactory
 * @author          Andres Oliva 
 * @created         30 / 07 / 2020
 * @description     Description of your code
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *              No.     Date            Author                  Description
 *              ----    ------------    --------------------    ----------------------------------------------
 * @version     1.0     2020-07-30      Andres Oliva            Changes desription
 *
**************************************************************************************************************/
@isTest
public with sharing class AFOG_AutosCrearPedidoUNOEE_tst {
  
    /*********************************************************************************************************
    * @name            sentOrderToUNOEE_WitoutOppLines
    * @author          Andres Oliva <andresolivag@gmail.com>
    * @created         30 / 07 / 2020
    * @description     Description of your code
    * @param           String param : Explanation
    * @return          Explanation of the return value
   **********************************************************************************************************/
    static testMethod void sentOrderToUNOEE_WitoutOppLines() {
        Pricebook2           objPricebookStand      =   createDataDactory.createPricebookId( true, 'Standard Price Book' ); 
        Pricebook2           objPricebook           =   createDataDactory.createPricebookId( true, 'Precios Usados' );
        account              objAcc                 =   createDataDactory.createAccount( true , 'Account_Test', '102547845');
        opportunity          objOpp                 =   createDataDactory.createOpportunityUNOE( true , objAcc.Id, objPricebook.id);     
        test.StartTest();
            AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id );        
        test.StopTest();       
    }   
    
    /*********************************************************************************************************
    * @name            sentOrderToUNOEE_WithOppLines
    * @author          Andres Oliva <andresolivag@gmail.com>
    * @created         30 / 07 / 2020
    * @description     Description of your code
    * @param           String param : Explanation
    * @return          Explanation of the return value
   **********************************************************************************************************/
    static testMethod void sentOrderToUNOEE_WithOppLines() {
        //Create Product
        Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile');
        Insert pro;
        
        //Instantiate the Pricebook2 record with StandardPricebookId
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        
        //Execute an update DML on the Pricebook2 record, to make IsStandard to true
        Update standardPricebook;
        
        //Query for the Pricebook2 record, to check IsStandard field
        standardPricebook = [SELECT Id, IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
        //It should return true
        System.assertEquals(true, standardPricebook.IsStandard);      
        
        //Create the PricebookEntry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = pro.Id,
            UnitPrice = 1020,
            IsActive = true
        );
        Insert pbe;        
        //Query the PricebookEntry record
        pbe = [SELECT Id, Pricebook2.IsStandard FROM PricebookEntry];
       // Pricebook2           objPricebook             =   createDataDactory.createPricebookId( true, 'Precios Usados' );       
        account             objAcc                     =   createDataDactory.createAccount( true , 'Account_Test', '102547845');
        RecordType          recTypEmpresa              = [Select Id, DeveloperName From RecordType Where SobjectType = 'Account' and DeveloperName ='AM_CUE_Cuenta_empresarial' Limit 1];
       
        /*account             objAcc2                     =   createDataDactory.createAccount( false , 'Account_Test empresa', '182547845');
        objAcc2.PersonEmail = 'finance@email.com';
        objAcc2.recordTypeId = recTypEmpresa.Id;
        insert objAcc2;*/
        opportunity         objOpp                     =   createDataDactory.createOpportunityUNOE( true , objAcc.Id, standardPricebook.id );
        Product2            objProduct                 =   createDataDactory.createProduct2( true );        
        RecordType          recTyp                     = [Select Id, DeveloperName From RecordType Where SobjectType = 'Account' and DeveloperName ='AM_CUE_Persona_natural' Limit 1];
        Concesionario__c    objConces                  =   createDataDactory.createConcesionario( true );
       // PricebookEntry       objPricebEntryStandar  =   createDataDactory.createPricebookEntry(true, objProduct.Id, standardPricebook.id  );
       // PricebookEntry       objPricebEntry         =   createDataDactory.createPricebookEntry(true, objProduct.Id, objPricebook.Id );
        opportunityLineItem  objOpporLine               =   createDataDactory.createOpportunityLineItem( true , objProduct.Id ,objOpp.id );
        test.StartTest();
             AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id ); 
             objOpp.Se_creo_pedido_en_UNOEE__c = true;
             update objOpp;         
             AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id ); 
             objOpp.Se_creo_pedido_en_UNOEE__c = false;
             objOpp.Vitrina_de_despacho__c =null;
             objOpp.Order_Generated__c = true;
             update objOpp;
             AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id ); 
             objOpp.Vitrina_de_despacho__c = objConces.id;            
             //objOpp.Order_Generated__c = false;
             objOpp.Vitrina__c = null;
             update objOpp;
             AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id ); 
             objOpp.Notas_de_despacho__c ='notes';
             update objOpp;             
             objAcc.RecordTypeId = recTyp.id;
             update objAcc;
             AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id );
             objAcc.Actividad_economica__c = 'Comercializadora';
             update objAcc;
             AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id );  
             /*objAcc.recordtypeid= null;
             update  objAcc;
             objOpp.Forma_de_pago__c = 'Contado';
             update objOpp;
             AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id ); */ 

             
        test.StopTest();       
    }  

    /*********************************************************************************************************
    * @name            sentOrderToUNOEE_WithOppLines
    * @author          Andres Oliva <andresolivag@gmail.com>
    * @created         30 / 07 / 2020
    * @description     Description of your code
    * @param           String param : Explanation
    * @return          Explanation of the return value
   **********************************************************************************************************/
    static testMethod void sentOrderToUNOEE_WithOppLines_other() {
        //Create Product
        Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile');
        Insert pro;
        
        //Instantiate the Pricebook2 record with StandardPricebookId
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        
        //Execute an update DML on the Pricebook2 record, to make IsStandard to true
        Update standardPricebook;
        
        //Query for the Pricebook2 record, to check IsStandard field
        standardPricebook = [SELECT Id, IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
        //It should return true
        System.assertEquals(true, standardPricebook.IsStandard);      
        
        //Create the PricebookEntry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = pro.Id,
            UnitPrice = 1020,
            IsActive = true
        );
        Insert pbe;        
        //Query the PricebookEntry record
        pbe = [SELECT Id, Pricebook2.IsStandard FROM PricebookEntry];     
        account             objAcc                     =    createDataDactory.createAccount( true , 'Account_Test', '102547845');
        account             objAccFacturar             =    createDataDactory.createAccount( true , 'Account_Test', '102547845');
        RecordType          recTypEmpresa              =    [Select Id, DeveloperName From RecordType Where SobjectType = 'Account' and DeveloperName ='AM_CUE_Cuenta_empresarial' Limit 1];
        opportunity         objOpp                     =    createDataDactory.createOpportunityUNOE( true , objAcc.Id, standardPricebook.id );
        Product2            objProduct                 =    createDataDactory.createProduct2( true );        
        RecordType          recTyp                     =    [Select Id, DeveloperName From RecordType Where SobjectType = 'Account' and DeveloperName ='AM_CUE_Persona_natural' Limit 1];
        Concesionario__c    objConces                  =    createDataDactory.createConcesionario( true );
        opportunityLineItem  objOpporLine              =    createDataDactory.createOpportunityLineItem( true , objProduct.Id ,objOpp.id );
        test.StartTest();
                
                objOpp.Vitrina_de_despacho__c           = null;
                objOpp.Order_Generated__c               = true;
                objOpp.Vitrina_de_despacho__c           = objConces.id;            
                objOpp.Vitrina__c                       = null;
                objOpp.Notas_de_despacho__c             = 'notes';
                objOpp.Forma_de_pago__c                 = 'Contado';
                update objOpp; 

                objAcc.AM_Via_principal__c              =   'calle';
                objAcc.Actividad_economica__c           =   'Comercializadora';
                objAcc.recordtypeid= null;    
                update  objAcc;

            AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id ); 

                objAcc.AM_Via_principal__c                  = '';   
                update  objAcc; 

                objAccFacturar.Actividad_economica__c       = null;
                update objAccFacturar;

                objOpp.Facturar_a_nombre_de__c              =  objAccFacturar.Id;
                update objOpp;

            AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id ); 
            
        test.StopTest();       
    }  

    /*********************************************************************************************************
    * @name            sentOrderToUNOEE_WithOppLines
    * @author          Andres Oliva <andresolivag@gmail.com>
    * @created         30 / 07 / 2020
    * @description     Description of your code
    * @param           String param : Explanation
    * @return          Explanation of the return value
    **********************************************************************************************************/
    static testMethod void sentOrderToUNOEE_WithOppLines_other_v2() {
        //Create Product
        Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile');
        Insert pro;
        
        //Instantiate the Pricebook2 record with StandardPricebookId
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        
        //Execute an update DML on the Pricebook2 record, to make IsStandard to true
        Update standardPricebook;
        
        //Query for the Pricebook2 record, to check IsStandard field
        standardPricebook = [SELECT Id, IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
        //It should return true
        System.assertEquals(true, standardPricebook.IsStandard);      
        
        //Create the PricebookEntry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = pro.Id,
            UnitPrice = 1020,
            IsActive = true
        );
        Insert pbe;        
        //Query the PricebookEntry record
        pbe = [SELECT Id, Pricebook2.IsStandard FROM PricebookEntry];     
        account             objAcc                     =    createDataDactory.createAccount( true , 'Account_Test', '102547845');
        account             objAccFacturar             =    createDataDactory.createAccount( false , 'Account 65',  '102548458');
        objAccFacturar.PersonEmail = 'facturar@test.com';
        objAccFacturar.Actividad_economica__c       = null;
        insert objAccFacturar;
        RecordType          recTypEmpresa              =    [Select Id, DeveloperName From RecordType Where SobjectType = 'Account' and DeveloperName ='AM_CUE_Cuenta_empresarial' Limit 1];
        opportunity         objOpp                     =    createDataDactory.createOpportunityUNOE( true , objAcc.Id, standardPricebook.id );
        Product2            objProduct                 =    createDataDactory.createProduct2( true );        
        RecordType          recTyp                     =    [Select Id, DeveloperName From RecordType Where SobjectType = 'Account' and DeveloperName ='AM_CUE_Persona_natural' Limit 1];
        Concesionario__c    objConces                  =    createDataDactory.createConcesionario( true );
        opportunityLineItem  objOpporLine              =    createDataDactory.createOpportunityLineItem( true , objProduct.Id ,objOpp.id );
        test.StartTest();
          
                objAcc.AM_Via_principal__c              = 'AV';   
                objAcc.Actividad_economica__c           =   'Comercializadora';
                objAcc.AM_Literal_via_principal__c      = 'L';    
                objAcc.AM_Orientacion_via_principal__c  = 'Norte';      
                objAcc.AM_Literal_via_secundaria__c     = 'as';
                objAcc.AM_BIS2__c                       = true;
                objAcc.AM_Orientacion_via_secundaria__c = 'Oeste';
                objAcc.AM_ID_cuadra__c                  = 'sd';
                objAcc.AM_Complemento__c                = 'Complemento';                
                objAcc.AM_Numero_via_principal__c       = 39;
                objAcc.AM_Ocupacion_pc__c               = 'Empleado';
                update  objAcc; 

                update objAccFacturar;
                objOpp.Facturar_a_nombre_de__c              = objAccFacturar.Id;
                objOpp.Vitrina_de_despacho__c               = objConces.id;
                objOpp.Order_Generated__c                   = true;
                objOpp.Notas_de_despacho__c                 = 'notas';
                update objOpp;

            AutosCrearPedidoEnUNOEE.EnviarPedido( objOpp.Id ); 
            
        test.StopTest();       
    }  
}