force-app/main/default/objects/Account/fields/Concesionario__c.field-meta.xml
<CustomField>
    <fullName>Concesionario__c</fullName>
    <formula>TEXT(Owner.AM_Concesionario__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Concesionario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Concesionario__c/Concesionario__c.object-meta.xml
<CustomObject>
    <description>En este objeto se maneja la información para indicar el concesionario al cual pertenece cada usuario del sistema.</description>
    <label>Concesionario / Vitrina</label>
    <nameField>
        <label>Concesionario motos / Vitrina Autos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Concesionarios / Vitrinas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Concesionario__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agencia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agencia2__c.field-meta.xml
<CustomField>
    <fullName>Agencia2__c</fullName>
    <formula>Concesionario__r.Codigo_de_agencia__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agencia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Concesionario2__c.field-meta.xml
<CustomField>
    <fullName>Concesionario2__c</fullName>
    <formula>Concesionario__r.Codigo_concesionario__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Concesionario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Concesionario__c.field-meta.xml
<CustomField>
    <fullName>Concesionario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concesionario</label>
    <referenceTo>Concesionario__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/clsMotosVentasMesPasado.cls
public with sharing class clsMotosVentasMesPasado {
    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getOppsLastMonth(){
        try {
            return [Select Id, Owner.Name, StageName, Agencia__c, Agencia2__c,Concesionario__c, Concesionario2__c,Account.Name, Name, Amount,Probability, CloseDate, CreatedDate from Opportunity limit 100];    
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static Integer getTotalOppsLastMonth(){
        try {
            return 777;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}